part of 'app_theme.dart';

class LightColors {
  static ColorScheme get colors => const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff006970),
        surfaceTint: Color(0xff006970),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xff9df0f8),
        onPrimaryContainer: Color(0xff002022),
        secondary: Color(0xff4a6365),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffcce8ea),
        onSecondaryContainer: Color(0xff051f21),
        tertiary: Color(0xff4f5f7d),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffd7e2ff),
        onTertiaryContainer: Color(0xff0a1b36),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff410002),
        surface: Color(0xfff4fafb),
        onSurface: Color(0xff161d1d),
        onSurfaceVariant: Color(0xff3f4849),
        outline: Color(0xff6f797a),
        outlineVariant: Color(0xffbec8c9),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff2b3232),
        inversePrimary: Color(0xff80d4db),
        primaryFixed: Color(0xff9df0f8),
        onPrimaryFixed: Color(0xff002022),
        primaryFixedDim: Color(0xff80d4db),
        onPrimaryFixedVariant: Color(0xff004f54),
        secondaryFixed: Color(0xffcce8ea),
        onSecondaryFixed: Color(0xff051f21),
        secondaryFixedDim: Color(0xffb1cbce),
        onSecondaryFixedVariant: Color(0xff324b4d),
        tertiaryFixed: Color(0xffd7e2ff),
        onTertiaryFixed: Color(0xff0a1b36),
        tertiaryFixedDim: Color(0xffb7c7ea),
        onTertiaryFixedVariant: Color(0xff384764),
        surfaceDim: Color(0xffd5dbdb),
        surfaceBright: Color(0xfff4fafb),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xffeff5f5),
        surfaceContainer: Color(0xffe9efef),
        surfaceContainerHigh: Color(0xffe3e9ea),
        surfaceContainerHighest: Color(0xffdee4e4),
      );
}
